services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt
      && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--port", "3000", "--host"]
