version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6332:6333"