version: '3.11'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt
      && uvicorn main:app --host 0.0.0.0 --port 8000"